name: kistpay_chikoo
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  intl: ^0.18.0
  pin_code_fields:
  camera: ^0.10.5+2
  webview_flutter: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - packages/kistpay_chikoo/assets/images/easypaisa.png
    - packages/kistpay_chikoo/assets/images/image_not_found.png
    - packages/kistpay_chikoo/assets/images/img_arrowdown.svg
    - packages/kistpay_chikoo/assets/images/img_arrowdown_gray_700_01.svg
    - packages/kistpay_chikoo/assets/images/img_arrowleft.svg
    - packages/kistpay_chikoo/assets/images/img_arrowleft_indigo_400.svg
    - packages/kistpay_chikoo/assets/images/img_arrowright.svg
    - packages/kistpay_chikoo/assets/images/img_arrowup.svg
    - packages/kistpay_chikoo/assets/images/img_bluetoothicon.svg
    - packages/kistpay_chikoo/assets/images/img_car.svg
    - packages/kistpay_chikoo/assets/images/img_file.svg
    - packages/kistpay_chikoo/assets/images/img_g10.svg
    - packages/kistpay_chikoo/assets/images/img_icon.svg
    - packages/kistpay_chikoo/assets/images/img_icon_gray_800_01.svg
    - packages/kistpay_chikoo/assets/images/img_image57.png
    - packages/kistpay_chikoo/assets/images/img_rectangle6.svg
    - packages/kistpay_chikoo/assets/images/img_redminote11.png
    - packages/kistpay_chikoo/assets/images/img_signal.svg
    - packages/kistpay_chikoo/assets/images/img_television.svg
    - packages/kistpay_chikoo/assets/images/img_toggleradiobu.svg
    - packages/kistpay_chikoo/assets/images/img_toggleradiobu_white_a700.svg
    - packages/kistpay_chikoo/assets/images/img_undrawconfirmed81ex1.svg
    - packages/kistpay_chikoo/assets/images/jazzcash.png
    - packages/kistpay_chikoo/assets/images/newApplocation.svg
    - packages/kistpay_chikoo/assets/images/payfast.png
    - packages/kistpay_chikoo/assets/images/payments.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: packages/kistpay_chikoo/assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Mulish
      fonts:
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanExtraBold.ttf
          weight: 800
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanRegular.ttf
          weight: 400
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: packages/kistpay_chikoo/assets/fonts/MulishItalicRegular.ttf
          weight: 400
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanSemiBold.ttf
          weight: 600
        - asset: packages/kistpay_chikoo/assets/fonts/MulishRomanLight.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: packages/kistpay_chikoo/assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: packages/kistpay_chikoo/assets/fonts/RobotoRomanBold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: packages/kistpay_chikoo/assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: packages/kistpay_chikoo/assets/fonts/MontserratRomanBold.ttf
          weight: 700
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
